"""create tickets bookings

Revision ID: 2ab7ccc49f4d
Revises: 
Create Date: 2026-08-16 09:21:11.854293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ab7ccc49f4d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('section', sa.String(length=100), nullable=False),
    sa.Column('row_name', sa.String(length=100), nullable=False),
    sa.Column('seat_label', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'HELD', 'BOOKED', name='ticketstatus'), nullable=False),
    sa.Column('hold_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'section', 'row_name', 'seat_label', name='uq_ticket_event_seat')
    )
    op.create_index(op.f('ix_tickets_event_id'), 'tickets', ['event_id'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_subject', sa.String(length=255), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'EXPIRED', name='bookingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_event_id'), 'bookings', ['event_id'], unique=False)
    op.create_index(op.f('ix_bookings_user_subject'), 'bookings', ['user_subject'], unique=False)
    # ### end Alembic commands ###

    # Defense-in-depth (hand-added, not autogenerated): at most one active
    # (pending/confirmed) booking per ticket, enforced at the DB level
    # independent of whichever TicketHoldStrategy is running (§6).
    op.create_index(
        'uq_bookings_active_ticket',
        'bookings',
        ['ticket_id'],
        unique=True,
        postgresql_where=sa.text("status IN ('PENDING', 'CONFIRMED')"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('uq_bookings_active_ticket', table_name='bookings')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_user_subject'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_event_id'), table_name='bookings')
    op.drop_table('bookings')
    sa.Enum(name='bookingstatus').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_event_id'), table_name='tickets')
    op.drop_table('tickets')
    sa.Enum(name='ticketstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
